### ISSUE TITLE
Key error 'image make'

### ISSUE THREAD

**Issue by virginsince1997** [basnijholt/instacron#7]
Hello I got this error while trying to run Instagram.py

```
root@host:~/instacron# python3.6 instacron.py
Didn't find a matching template.
Getting info from EXIF data.
Traceback (most recent call last):
  File "instacron.py", line 155, in get_photo_info
    raise Exception("Didn't find a matching template.")
Exception: Didn't find a matching template.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "instacron.py", line 374, in <module>
    main()
  File "instacron.py", line 353, in main
    caption += get_caption(photo)
  File "instacron.py", line 207, in get_caption
    city, country, date = get_photo_info(fname)
  File "instacron.py", line 159, in get_photo_info
    return get_info_from_exif(photo)
  File "instacron.py", line 139, in get_info_from_exif
    date = dateutil.parser.parse(tags['Image DateTime'].printable)
KeyError: 'Image DateTime'
root@host:~/instacron# python3.6 instacron.py
Traceback (most recent call last):
  File "instacron.py", line 374, in <module>
    main()
  File "instacron.py", line 353, in main
    caption += get_caption(photo)
  File "instacron.py", line 220, in get_caption
    caption += spacer + get_camera_settings(fname) + spacer
  File "instacron.py", line 195, in get_camera_settings
    brand = tags['Image Make'].printable
KeyError: 'Image Make'
root@host:~/instacron# python3.6 instacron.py
Traceback (most recent call last):
  File "instacron.py", line 374, in <module>
    main()
  File "instacron.py", line 353, in main
    caption += get_caption(photo)
  File "instacron.py", line 220, in get_caption
    caption += spacer + get_camera_settings(fname) + spacer
  File "instacron.py", line 195, in get_camera_settings
    brand = tags['Image Make'].printable
KeyError: 'Image Make'

```

**Comment by JWPapi** [comment]
how did you solve this?

**Comment by basnijholt** [comment]
@JWPapi I think it might be because your photo doesn't have the right camera information. I could add a try except and not add the camera info if it isn't available.

**Comment by JWPapi** [comment]
Yeah I have deleted it just on my script, because I don't plan to need it. For me you don't have to change it @basnijholt. I deleted a couple of stuff out which is very smart and cool made by you, but for my case I need a simple uploader thats it, so less is better and less chances for errors.
