### ISSUE TITLE
help RuntimeError: Unsupported format

### ISSUE THREAD

**Issue by roncam82** [basnijholt/instacron#9]
hi,

can you helpe me on the below error please ?

RuntimeError: Unsupported format

**Comment by roncam82** [comment]
any help ?

**Comment by basnijholt** [comment]
Could you try it with a different file, just to test. 

Also, you might know this, but changing the extension from .PNG to .JPG doesn't actually make it a JPG.

**Comment by roncam82** [comment]
yes yes i know

**Comment by roncam82** [comment]
C:\Users\Administrator\Documents\GitHub\instacron>python instacron.py
Traceback (most recent call last):
  File "instacron.py", line 374, in <module>
    main()
  File "instacron.py", line 348, in main
    photo = choose_random_photo(uploaded_file, photo_folder)
  File "instacron.py", line 71, in choose_random_photo
    photo = random.choice(photos)  # choose a random photo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\random.py", line 261, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
